### ISSUE TITLE
Ignores folders

### ISSUE THREAD

**Issue by Xillez** [AaronTheNerd/ClearDirectory#1]
Nice extension, love it!

It seems like it doesn't delete recursively, so sub-folders remain. Could this be added? Maybe as a toggle-able setting like `Recursive deletion`?

**Comment by AaronTheNerd** [comment]
Thank you for your feedback! 

Created commit: c181edf04106772d6430d659a1f5cd81664b4f84 to resolve this issue.

This change has been included in version 0.1.0 and is toggleable through the setting `cleardirectory.deleteSubdirectories`
